// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fevbhenzheknvvdvzfik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZldmJoZW56aGVrbnZ2ZHZ6ZmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDM2NzEsImV4cCI6MjA2MjM3OTY3MX0.4E7UsctwUz8u_8TEhIo3b03A39is5_pBvxdYa0gnTfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);